export const WHEEL_SPEED = 0.3;
export const MAX_SCROLLBAR_LENGTH = 80;
export const PROGRESSBAR_DELAY = 400;
export const PROGRESSBAR_STEP = 10;
export const RUNNER_PROGRESSBAR_DELAY = 400;
export const RUNNER_PROGRESSBAR_STEP = 10;
export const CHALLENGE_MANAGER_REDIRECT_TIME = 2000;
export const CHALLENGE_PASSED_REDIRECT_TIME = 3000;